/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/movies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Catálogo paginado
     * @description Lista os filmes com busca por título, filtros por gênero e ano, e ordenação.
     */
    get: operations['list_movies_api_v1_movies_get'];
    put?: never;
    /**
     * Cadastrar filme
     * @description Cadastra um filme; diretores são reaproveitados pelo nome ou criados.
     */
    post: operations['create_movie_api_v1_movies_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/movies/{sk_movie_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detalhe do filme
     * @description Devolve o filme com gêneros, pessoas, produtoras, performance e média das avaliações.
     */
    get: operations['get_movie_api_v1_movies__sk_movie_id__get'];
    put?: never;
    post?: never;
    /**
     * Remover filme
     * @description Remove o filme junto com suas ligações, performance e avaliações.
     */
    delete: operations['delete_movie_api_v1_movies__sk_movie_id__delete'];
    options?: never;
    head?: never;
    /**
     * Atualizar filme (parcial)
     * @description Altera só os campos enviados; ``diretores`` e ``genre_ids`` substituem as listas.
     */
    patch: operations['update_movie_api_v1_movies__sk_movie_id__patch'];
    trace?: never;
  };
  '/api/v1/movies/{sk_movie_id}/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Avaliações do filme (mais recentes primeiro)
     * @description Lista as avaliações do filme; ``created_at`` sai em UTC (sufixo ``Z``).
     */
    get: operations['list_reviews_api_v1_movies__sk_movie_id__reviews_get'];
    put?: never;
    /**
     * Avaliar filme
     * @description Grava a avaliação (nota de 0 a 10) e devolve a média e a quantidade atualizadas.
     */
    post: operations['create_review_api_v1_movies__sk_movie_id__reviews_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/genres': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lista de gêneros
     * @description Lista todos os gêneros em ordem alfabética.
     */
    get: operations['list_genres_api_v1_genres_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Status da API */
    get: operations['health_check_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ErrorItem
     * @description Erro associado a um campo da requisição.
     */
    ErrorItem: {
      /** Field */
      field: string;
      /** Message */
      message: string;
    };
    /**
     * ErrorResponse
     * @description Formato único das respostas de erro da API.
     * @example {
     *       "detail": "Dados inválidos.",
     *       "errors": [
     *         {
     *           "field": "nota",
     *           "message": "Deve ser menor ou igual a 10."
     *         }
     *       ]
     *     }
     * @example {
     *       "detail": "Filme não encontrado."
     *     }
     */
    ErrorResponse: {
      /** Detail */
      detail: string;
      /** Errors */
      errors?: components['schemas']['ErrorItem'][] | null;
    };
    /**
     * GenreRead
     * @description Gênero disponível para filtros e formulários.
     */
    GenreRead: {
      /** Sk Genre Id */
      sk_genre_id: string;
      /** Nome Genero */
      nome_genero: string;
    };
    /**
     * MovieCreate
     * @description Dados para cadastrar um filme. O ``id_filme`` é gerado pelo backend.
     * @example {
     *       "ano_lancamento": 2024,
     *       "data_lancamento": "2024-05-10",
     *       "diretores": [
     *         "Fulana de Tal"
     *       ],
     *       "duracao_minutos": 120,
     *       "genre_ids": [
     *         "<sk_genre_id>"
     *       ],
     *       "sinopse": "Uma história sobre…",
     *       "titulo": "O Filme"
     *     }
     */
    MovieCreate: {
      /** Titulo */
      titulo: string;
      /**
       * Diretores
       * @description Nomes dos diretores
       */
      diretores?: string[];
      /** Ano Lancamento */
      ano_lancamento?: number | null;
      /**
       * Genre Ids
       * @description sk_genre_id dos gêneros
       */
      genre_ids?: string[];
      /** Sinopse */
      sinopse?: string | null;
      /** Duracao Minutos */
      duracao_minutos?: number | null;
      /** Data Lancamento */
      data_lancamento?: string | null;
      /** Url Poster */
      url_poster?: string | null;
      /** Url Backdrop */
      url_backdrop?: string | null;
    };
    /**
     * MovieDetail
     * @description Filme completo para a página de detalhe (sem as avaliações individuais).
     */
    MovieDetail: {
      /** Sk Movie Id */
      sk_movie_id: string;
      /** Id Filme */
      id_filme: string;
      /** Titulo */
      titulo: string;
      /** Data Lancamento */
      data_lancamento: string | null;
      /** Ano Lancamento */
      ano_lancamento: number | null;
      /** Duracao Minutos */
      duracao_minutos: number | null;
      /** Status Filme */
      status_filme: string | null;
      /** Sinopse */
      sinopse: string | null;
      /** Url Poster */
      url_poster: string | null;
      /** Url Backdrop */
      url_backdrop: string | null;
      /** Generos */
      generos: string[];
      /** Diretores */
      diretores: string[];
      /** Roteiristas */
      roteiristas: string[];
      /** Elenco */
      elenco: string[];
      /** Produtoras */
      produtoras: string[];
      performance: components['schemas']['MoviePerformance'] | null;
      /** Nota Media */
      nota_media: number | null;
      /** Qtd Avaliacoes */
      qtd_avaliacoes: number;
    };
    /**
     * MovieListItem
     * @description Filme resumido para a listagem do catálogo.
     */
    MovieListItem: {
      /** Sk Movie Id */
      sk_movie_id: string;
      /** Titulo */
      titulo: string;
      /** Ano Lancamento */
      ano_lancamento: number | null;
      /** Url Poster */
      url_poster: string | null;
      /** Generos */
      generos: string[];
      /** Nota Media */
      nota_media: number | null;
      /** Qtd Avaliacoes */
      qtd_avaliacoes: number;
    };
    /**
     * MoviePerformance
     * @description Métricas financeiras e de engajamento do filme, como estão no banco.
     *
     *     Os valores monetários saem como número (e não como string, que é o padrão do Pydantic
     *     para ``Decimal``), o que simplifica o consumo pelo front.
     */
    MoviePerformance: {
      /** Orcamento Usd */
      orcamento_usd: number | null;
      /** Receita Usd */
      receita_usd: number | null;
      /** Lucro Usd */
      lucro_usd: number;
      /** Orcamento Brl */
      orcamento_brl: number | null;
      /** Receita Brl */
      receita_brl: number | null;
      /** Lucro Brl */
      lucro_brl: number;
      /** Popularidade */
      popularidade: number | null;
      /** Nota Tmdb */
      nota_tmdb: number | null;
      /** Qtd Tmdb */
      qtd_tmdb: number | null;
      /** Nota Imdb */
      nota_imdb: number | null;
      /** Qtd Imdb */
      qtd_imdb: number | null;
    };
    /**
     * MovieSort
     * @description Campos aceitos para ordenar o catálogo.
     * @enum {string}
     */
    MovieSort: 'popularidade' | 'titulo' | 'ano_lancamento' | 'nota_media';
    /**
     * MovieUpdate
     * @description Atualização parcial: só os campos enviados são alterados.
     *
     *     ``diretores`` substitui apenas os diretores (elenco e roteiristas ficam);
     *     ``genre_ids`` substitui todos os gêneros.
     * @example {
     *       "duracao_minutos": 95,
     *       "sinopse": "Nova sinopse."
     *     }
     */
    MovieUpdate: {
      /** Titulo */
      titulo?: string | null;
      /** Diretores */
      diretores?: string[] | null;
      /** Ano Lancamento */
      ano_lancamento?: number | null;
      /** Genre Ids */
      genre_ids?: string[] | null;
      /** Sinopse */
      sinopse?: string | null;
      /** Duracao Minutos */
      duracao_minutos?: number | null;
      /** Data Lancamento */
      data_lancamento?: string | null;
      /** Url Poster */
      url_poster?: string | null;
      /** Url Backdrop */
      url_backdrop?: string | null;
    };
    /** Page[MovieListItem] */
    Page_MovieListItem_: {
      /** Items */
      items: components['schemas']['MovieListItem'][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Pages */
      pages: number;
    };
    /** Page[ReviewRead] */
    Page_ReviewRead_: {
      /** Items */
      items: components['schemas']['ReviewRead'][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Pages */
      pages: number;
    };
    /**
     * ReviewCreate
     * @description Dados para avaliar um filme (nota de 0 a 10 e resenha).
     * @example {
     *       "comentario": "Roteiro excelente.",
     *       "nome": "Ana",
     *       "nota": 8.5
     *     }
     */
    ReviewCreate: {
      /** Nome */
      nome: string;
      /** Nota */
      nota: number;
      /** Comentario */
      comentario: string;
    };
    /**
     * ReviewCreated
     * @description Avaliação recém-criada e o resumo de avaliações do filme já recalculado.
     */
    ReviewCreated: {
      avaliacao: components['schemas']['ReviewRead'];
      /** Nota Media */
      nota_media: number;
      /** Qtd Avaliacoes */
      qtd_avaliacoes: number;
    };
    /**
     * ReviewRead
     * @description Avaliação individual de um filme.
     */
    ReviewRead: {
      /** Sk Movie Review Id */
      sk_movie_review_id: string;
      /** Nome */
      nome: string;
      /** Nota */
      nota: number;
      /** Comentario */
      comentario: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * SortOrder
     * @description Direção da ordenação.
     * @enum {string}
     */
    SortOrder: 'asc' | 'desc';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_movies_api_v1_movies_get: {
    parameters: {
      query?: {
        /** @description Página (começa em 1) */
        page?: number;
        /** @description Itens por página */
        page_size?: number;
        /** @description Trecho do título (sem diferenciar maiúsculas/minúsculas) */
        q?: string | null;
        /** @description sk_genre_id do gênero */
        genre_id?: string | null;
        /** @description Ano de lançamento */
        year?: number | null;
        /** @description Campo de ordenação */
        sort?: components['schemas']['MovieSort'];
        /** @description Direção; padrão desc, exceto para titulo (asc) */
        order?: components['schemas']['SortOrder'] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_MovieListItem_'];
        };
      };
      /** @description Parâmetros de consulta inválidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_movie_api_v1_movies_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MovieCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovieDetail'];
        };
      };
      /** @description Dados inválidos ou gênero inexistente */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_movie_api_v1_movies__sk_movie_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sk_movie_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovieDetail'];
        };
      };
      /** @description Filme não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Dados inválidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  delete_movie_api_v1_movies__sk_movie_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sk_movie_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Filme não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Dados inválidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  update_movie_api_v1_movies__sk_movie_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sk_movie_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MovieUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovieDetail'];
        };
      };
      /** @description Filme não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Dados inválidos ou gênero inexistente */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_reviews_api_v1_movies__sk_movie_id__reviews_get: {
    parameters: {
      query?: {
        /** @description Página (começa em 1) */
        page?: number;
        /** @description Itens por página */
        page_size?: number;
      };
      header?: never;
      path: {
        sk_movie_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_ReviewRead_'];
        };
      };
      /** @description Filme não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Parâmetros de consulta inválidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_review_api_v1_movies__sk_movie_id__reviews_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sk_movie_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReviewCreated'];
        };
      };
      /** @description Filme não encontrado */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Dados inválidos */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_genres_api_v1_genres_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenreRead'][];
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
}
